### PR TITLE
Unlimited inventory actions

### PR DESCRIPTION
**Pull request by Silvergriffon**
Option to enable unlimited inventory actions instead of 1 per turn.

### CODE REVIEW

**Review by ThyWoof — CHANGES_REQUESTED** [review]
Quick look tells me it’s changing more files than it should. For example, the change log. Can you validate if this was pushed with the latest changes in DEV?

**Comment by Silvergriffon** [comment]
It was, but there was some weirdness where it wanted to push back your last 3 commits like they were new commits, so I did something wrong there. Could that be the cause? I think I pushed it, had to rebase with your changes and pushed it again. It should really just be the patches to InventoryPanel and InventoryShortcutsPanel.

**Comment by Silvergriffon** [comment]
Let me know if you would like me to close the pull request and redo it again based on the latest dev sometime next week.

**Comment by Silvergriffon** [comment]
Closing Pull request and will resubmit

**Pull request closed without merging**
