### PR TITLE
PATCH: add a rule to grant adv to attacks that the target unable to see

### PR DESCRIPTION
**Pull request by HIEROT**
Tested in the master branch (Because by the time I pulled the dev branch it was under modification hence failed in compiling)
Now you can notice that when I attack the bandit without darkvision, I have advantage. And the adv and disadv cancel if both party don't have darkvision.
image
image

### CODE REVIEW

**Comment by HIEROT** [comment]
Oh another TODO: add a switch in the setting panel to on/off this modification.

**Comment by ThyWoof** [comment]
Yep, DEV now is on POI version. Can you hold this one 24 hrs and resubmit once we publish 1.5?

**Review by ThyWoof — APPROVED** [review]

**Comment by HIEROT** [comment]
Invisibility and this feature will grant two stacking advantages, which doesn't make sense if you calculate the result using the vanilla solasta adv rules because they both cite the same rule (combat with enemies that cannot be seen). But if you switch on official adv rules, it seems doesn't matter. That being said, a better solution may be moving this block of code to somewhere invisibility is handled and merging them, but I just haven't yet identify it.

**Comment by ThyWoof** [comment]
I tried patching RuleSetCharacter.CanSenseTarget to return true of target has greater invisibility and it works fine but condition gets removed. My problem now is to prevent this to happen. Not sure where in code it remove conditions based on failed senses

**Comment by ThyWoof** [comment]
By the way it ended up merged with a setting

**Comment by HIEROT** [comment]
Oh I tested a senario where darkness spell is covered. Currently, two characters without true sight, one insight and the other outside the affected region, will attack each other with disadvantage, which shouldn't be the case. It's true that my modification is far from perfect because only light condition is hard coded here :(. It's not difficult to fix this right at the location I modified, but a better solution may be like what you said, we should check if the two creatures can see each other and apply advantage rules accordingly (in a more elegant way)

**Pull request merged**
