### PR TITLE
More war dancer tweaks and some fixes

### PR DESCRIPTION
**Pull request by EnderWiggin**

### CODE REVIEW

**Comment by EnderWiggin** [comment]
closes #3497

**Review by HIEROT — APPROVED** [review]

**Comment by HIEROT** [comment]
lol,  I thought it was clicking a like(づ ●─● )づ

**Comment by EnderWiggin** [comment]
closes #3516

**Comment by EnderWiggin** [comment]
Closes #3525

**Review by ThyWoof — APPROVED** [review]

**Review by ThyWoof — APPROVED** [review]

**Pull request merged**
