### PR TITLE
Added Tidal Wave and prototype Watery Sphere spells.

### PR DESCRIPTION
**Pull request by Sigil9963**

### CODE REVIEW

**Review by ThyWoof — CHANGES_REQUESTED** [review]
Please ensure you always have the latest dev merged on your end before submitting a PR. Also, I won’t commit any changes to Tieflings as these got demoted from the mod and still only exist for backward compatibility.

**Comment by kloranger** [comment]
I thought I reverted the Tiefling changes. I'm not very familiar with Github.

**Comment by kloranger** [comment]
I think I fixed it.

**Comment by ThyWoof** [comment]
I'll defer this merge after the DLC. Lots of work still to prepare for that.

**Pull request closed without merging**
