### PR TITLE
Fixed bug where Chinese, Japanese and Korean did not wrap the line correctly

### PR DESCRIPTION
**Pull request by magicskysword**
# Why fix this
https://github.com/SolastaMods/SolastaUnfinishedBusiness/issues/3394
Solasta's way of wrapping text is to use Spaces to break up words, but there are no Spaces between characters in CJK(Chinese, Japanese and Korean), so there is a wrapping error.

# Principle of repair
Changed how to Split CJK text, and eliminates the spacing between CJK character.

# How to enable
This fix is switchable because I am concerned about the possible impact on other languages.(Although according to my tests there should be no other effect)
It's in Interface > Game UI > Campaigns and locations. I don't know where to put it right now.

### CODE REVIEW

**Review by ThyWoof — APPROVED** [review]

**Comment by kappa-maintainer** [comment]
If you are really concern about wrong wrapping on other languages, you can try using BreakIterator from unicode's official tool icu-dotnet

**Comment by ThyWoof** [comment]
Can you please open a discussion and share more? I don’t speak any Asian language at all and only recently decided support them.

**Comment by ThyWoof** [comment]
https://github.com/sillsdev/icu-dotnet @magicskysword

**Comment by magicskysword** [comment]
> If you are really concern about wrong wrapping on other languages, you can try using BreakIterator from unicode's official tool icu-dotnet

According to my tests, the ICU library is not suitable.It requires specifying the language type and will removes some code symbols incorrectly (such as "<sprite_index={0}>") . The library is also not platform-wide; each platform uses a different build. Just a single platform build is 25mb, which is too large.

**Pull request merged**
