### PR TITLE
Update Chinese translation for 1.4.33.77

### PR DESCRIPTION
**Pull request by magicskysword**

### CODE REVIEW

**Review by ThyWoof — APPROVED** [review]

**Review by ThyWoof — APPROVED** [review]

**Comment by ThyWoof** [comment]
image
was working on some translation changes so these still need help on CN.

**Comment by magicskysword** [comment]
I checked and the translations have been added to the file.Including new spell, new metaMagic and new subclass. There's probably nothing more to add.

**Comment by ThyWoof** [comment]
please review https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/29ce1317ce06ed5e7dd74734c1644a17e78a74c9

**Comment by magicskysword** [comment]
Ok, I will follow up and revise the follow-up translation tomorrow.

**Pull request merged**
